### ISSUE TITLE
add option to set a host path

### ISSUE THREAD

**Issue by mattdinsdale** [hotio/docker-readarr#4]
Can we have an option added to the xml so that there is a default option in unraid to add a path on the host where media is stored

**Comment by hotio** [comment]
It's bad practice to do this...easiest is to aline these paths with the download clients...

Wouldn't it be annoying if I made the container path's default `/defaults/hotioReadarrMediaFilesAreStoredHere`?

**Comment by mattdinsdale** [comment]
i meant it more of a blank path but to have the variable there that needs a path adding on creating

**Comment by hotio** [comment]
What's wrong with pushing a button 1 time to add a path?
